spring:
  datasource:
    url: jdbc:mysql://aa164h5rl2th2np.cayu63rfxn0v.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    username: terakoya
    password: terakoya
    driverClassname: com.mysql.jdbc.Driver
